name: Release - Publish Python package to PyPI

on:
  workflow_dispatch:

jobs:

  release-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2


      - name: Install uv
        uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174 # v5.4.0
        with:
          enable-cache: true


      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.x"


      - name: Build release distributions
        run: |
          uv build


      - name: Upload release distributions are artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: release-dists
          path: dist/


  pypi-publish:

    runs-on: ubuntu-latest

    environment: pypi

    needs:
      - release-build

    permissions:
      id-token: write

    steps:

      - name: Download release distributions artifact
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: release-dists
          path: dist/


      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
